apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-issuer
  namespace: argocd
  annotations:
    # Wait for the CRD to be created before syncing
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  project: default
  source:
    repoURL: https://github.com/khaykingleb/selfhosted-videochat.git
    targetRevision: backbone # TODO: HEAD
    path: kustomize/base/cert-manager
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
