serverName: videochat.khaykingleb.com
certManager:
  clusterIssuer: letsencrypt-prod
ingress:
  class: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
synapse:
  ingress:
    host: matrix.videochat.khaykingleb.com
matrixAuthenticationService:
  ingress:
    host: account.videochat.khaykingleb.com
matrixRTC:
  ingress:
    host: mrtc.videochat.khaykingleb.com
elementWeb:
  ingress:
    host: chat.videochat.khaykingleb.com
